---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: mysql
  :database: hooktastic_development
  :username: root
  :password: 
  :host: localhost

:test:
  <<: *defaults
  :database: hooktastic_test

:production:
  <<: *defaults
  :database: hooktastic_production